import About from "@/components/About";
import Head from "next/head";
import React from "react";


function AboutPage () {
return(
    <>
    <Head>
      <title>About Us</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.icon" />
    </Head>
    <main>
      <About />
    </main>
  </>
)
}

export default AboutPage;