import SizeGuide from "@/components/SizeGuide";
import Head from "next/head";
import React from "react";


function Size () {
return(
    <>
    <Head>
      <title>Size Guide</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <SizeGuide />
    </main>
  </>
)
}

export default Size;